[package]
name = "matrix_bot_api"
version = "0.2.0"
authors = ["zwieberl <donko@posteo.de>"]
description = """API for writing a bot for the Matrix messaging protocol"""
license = "MIT"
keywords = [ "matrix", "bot", "fractal" ]
repository = "https://github.com/zwieberl/matrix_bot_api"

[dependencies]
fractal-matrix-api = "3.29.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.2"

[dev-dependencies]
config = "0.8"
rand = "0.3"